version: "3.9"
services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=Admin
      - POSTGRES_PASSWORD=ArmorAdmin123
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"